version = 1

test_patterns = [
    "**/test/**"
]

exclude_patterns = [
    "build/**"
]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "kotlin"
enabled = true

[analyzers.meta]
runtime_version = "17"
language_version = "1.9"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true
