name: Android CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle Wrapper
      uses: actions/cache@v4.2.0
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts*', '**/gradle-wrapper.properties') }}

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: 34.0.0
        ndk: false
    
    - name: Grant Execute Permission for Gradlew
      run: chmod +x ./gradlew
    
    - name: Build Project
      run: ./gradlew assembleDebug
    
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
    
    - name: Run Instrumentation Tests
      run: ./gradlew connectedDebugAndroidTest
