name: Check

on: [ workflow_call ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle Wrapper
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts*', '**/gradle-wrapper.properties') }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 34.0.0
          ndk: false

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build App with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Report test coverage to DeepSource
        run: |
          # Tests have finished and a test coverage report is available
          # Install deepsource CLI
           curl https://deepsource.io/cli | sh
          # From the root directory, run the report coverage command
           ./bin/deepsource report --analyzer test-coverage --key kotlin --value-file build/reports/kover/xml/report.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

# FIXME: Temporary disabled, should be re-enabled when CI is configured and stable
#    - name: Build Android Test APK
#      run: ./gradlew assembleAndroidTest

#    - name: Run Android tests on Firebase Test Lab
#      uses: asadmansr/Firebase-Test-Lab-Action@v1.0
#      with:
#        arg-spec: 'android-device.yml:android-pixel-5'
#      env:
#        SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
