name: Lint

on: [ workflow_call ]

jobs:
  build:
    name: Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle Wrapper
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts*', '**/gradle-wrapper.properties') }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 34.0.0
          ndk: false

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build App with Gradle
        run: ./gradlew detekt spotlessCheck
