name: PR Checks

on:
  pull_request:
    branches:
      - master
      - release/*
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

# Ensure only one CI run per PR is active; a new event cancels the previous run
concurrency:
  group: pr-checks-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
